[tool.black]
line-length = 88
target-version = ['py37']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.vscode        # exclude a few common directories in the
    | \.git          # root of the project
    | \.__pycache__
    | \.pytest_cache
    | \.circleci
    | \venv
    | \Old
  )/
  | .flake8           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''